project:
  type: website
  output-dir: docs
  render:
    - report.qmd
    - slides.qmd

execute:
  echo: false   # hides code in final output
  warning: false
  message: false

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: article

bibliography: references.bib
csl: https://www.zotero.org/styles/apa
